### ISSUE TITLE
How is the adaptability in high dimension?

### ISSUE THREAD

**Issue by szt008** [ZJU-FAST-Lab/SDLP#1]
When the dimension is high, such as 10000 optimization variables and 100000 constraints, could the solver keep better 
 or same speed to solve as the general solvers?

**Comment by ZhepeiWang** [comment]
When the dimension of decision variables is high, the solver is not usable. Let us denote by **d** the dimension, by **n** the number of constraints. The time complexity of the solver is **O(d!n)**. We can see, when **d** is fixed as a small number (such as **d**<10), the complexity is optimal w.r.t. **n**, i.e., linear complexity. However, for large **d**, a general solver using primal-dual simplex or interior-point method will be far better.

Indeed, this solver is designed for computational geometry, since there are tons of problems whose dimension is 2, 3, or 4, and the constraint number is really large. Thus SDLP can only show its superior efficiency againt general LP solvers in this type of problems.

**Comment by szt008** [comment]
Thank you so much for your enthusiastic answer. 
Could you recommend some general linear programming solvers with a friendly Eigen or C++ interface? It would be better if it could be suitable for large-scale sparse linear programming problems.

**Comment by ZhepeiWang** [comment]
For general purpose LP, the GNU Linear Programming Kit (https://www.gnu.org/software/glpk/) is recommended. If you prefer an Eigen interface, there is also a wrapper (https://github.com/ZJU-FAST-Lab/GLPK_Interface).
